// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnJtcVidqIFbDSKNl3TEwYtOXOLqA-iPE',
    appId: '1:653873772952:web:caf66154875dc0e842d3ed',
    messagingSenderId: '653873772952',
    projectId: 'skindareapplication',
    authDomain: 'skindareapplication.firebaseapp.com',
    storageBucket: 'skindareapplication.firebasestorage.app',
    measurementId: 'G-5PF2N3X3EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCWfxwtyNUgdtBpTr238kdiVOFqoXjvxE',
    appId: '1:653873772952:android:c98a8efc5a3c05c042d3ed',
    messagingSenderId: '653873772952',
    projectId: 'skindareapplication',
    storageBucket: 'skindareapplication.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0hERPjfueJeAdR6AnIMQcYRzEzOYALes',
    appId: '1:653873772952:ios:cf7611359bd86e6c42d3ed',
    messagingSenderId: '653873772952',
    projectId: 'skindareapplication',
    storageBucket: 'skindareapplication.firebasestorage.app',
    iosBundleId: 'com.example.skindare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0hERPjfueJeAdR6AnIMQcYRzEzOYALes',
    appId: '1:653873772952:ios:cf7611359bd86e6c42d3ed',
    messagingSenderId: '653873772952',
    projectId: 'skindareapplication',
    storageBucket: 'skindareapplication.firebasestorage.app',
    iosBundleId: 'com.example.skindare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCnJtcVidqIFbDSKNl3TEwYtOXOLqA-iPE',
    appId: '1:653873772952:web:6df28722480a896342d3ed',
    messagingSenderId: '653873772952',
    projectId: 'skindareapplication',
    authDomain: 'skindareapplication.firebaseapp.com',
    storageBucket: 'skindareapplication.firebasestorage.app',
    measurementId: 'G-BGSVK8SGED',
  );
}
